# permissions for end users to edit deviceconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deviceconfig-editor-role
rules:
- apiGroups:
  - example.com
  resources:
  - deviceconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - example.com
  resources:
  - deviceconfigs/status
  verbs:
  - get
