# permissions for end users to view deviceconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deviceconfig-viewer-role
rules:
- apiGroups:
  - example.com
  resources:
  - deviceconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - example.com
  resources:
  - deviceconfigs/status
  verbs:
  - get
