// Code generated by MockGen. DO NOT EDIT.
// Source: nodeselector.go

// Package nodeselector is a generated GoMock package.
package nodeselector

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	v1alpha1 "github.com/mresvanis/he-sample-operator/api/v1alpha1"
)

// MockValidator is a mock of Validator interface.
type MockValidator struct {
	ctrl     *gomock.Controller
	recorder *MockValidatorMockRecorder
}

// MockValidatorMockRecorder is the mock recorder for MockValidator.
type MockValidatorMockRecorder struct {
	mock *MockValidator
}

// NewMockValidator creates a new mock instance.
func NewMockValidator(ctrl *gomock.Controller) *MockValidator {
	mock := &MockValidator{ctrl: ctrl}
	mock.recorder = &MockValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockValidator) EXPECT() *MockValidatorMockRecorder {
	return m.recorder
}

// CheckDeviceConfigForConflictingNodeSelector mocks base method.
func (m *MockValidator) CheckDeviceConfigForConflictingNodeSelector(ctx context.Context, cr *v1alpha1.DeviceConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckDeviceConfigForConflictingNodeSelector", ctx, cr)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckDeviceConfigForConflictingNodeSelector indicates an expected call of CheckDeviceConfigForConflictingNodeSelector.
func (mr *MockValidatorMockRecorder) CheckDeviceConfigForConflictingNodeSelector(ctx, cr interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckDeviceConfigForConflictingNodeSelector", reflect.TypeOf((*MockValidator)(nil).CheckDeviceConfigForConflictingNodeSelector), ctx, cr)
}
